id = "basedpyright"
name = "BasedPyright"
version = "0.0.1"
schema_version = 1
authors = ["Jose Miguel <miguelpintojose00@gmail.com>"]
description = "BasedPyright for zed."
repository = "https://github.com/m1guer/my-zed-extension"

[language_servers.basedpyright]
name = "BasedPyright"
language = "Python"

[grammers.python]
repository = "https://github.com/tree-sitter/tree-sitter-python"
